### PR TITLE
Added jenkinsfile for api-trips service

### PR DESCRIPTION
**Pull request by jonocarnie**
## Purpose
For issue #8 

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by rogersytai** [comment]
run test

**Comment by rogersytai** [comment]
run test

**Comment by jonocarnie** [comment]
run tests

**Comment by rogersytai** [comment]
run test

**Comment by jonocarnie** [comment]
new pr

**Pull request closed without merging**
