### PR TITLE
Poi jenkinsfile

### PR DESCRIPTION
**Pull request by piquet-h**
## Purpose
Docker build and push to ACR

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[X] Other... Build:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information
poi go

### CODE REVIEW

**Comment by piquet-h** [comment]
poi go

**Comment by piquet-h** [comment]
poi go!!

**Comment by rogersytai** [comment]
poi go

**Comment by rogersytai** [comment]
poi go!!

**Pull request merged**
